AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS CloudFormation Template For BankManagement Java App Resources'

Parameters:
  Principal:
    Type: String
    Default: arn:aws:iam::266735814394:role/silas-github-role
Resources:
  BankManagementECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: bank-management
      ImageScanningConfiguration:
        scanOnPush: true
      ImageTagMutability: MUTABLE

      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Sid: GitHubOIDCPushAccess
            Effect: Allow
            Principal:
              AWS: !Ref Principal
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
              - ecr:BatchGetImage
              - ecr:GetDownloadUrlForLayer
              - ecr:DescribeImages
              - ecr:ListImages

      Tags:
        - Key: Name
          Value: bank-management

